# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

"""Canonical next-step-suggestion guidelines — single-sourced.

Every surface that proposes analysis moves to the user follows this one text:

* the **persistent suggestion strip** (the chips above the chat input),
  generated by ``agents/agent_starter_questions.py`` — which embeds this text
  directly — on session start, after a charting run completes, and via the
  ideation button;
* the analyst agent, when the user **asks in chat** what to explore next (the
  core skill's "Suggesting next steps" section).

The analyst system prompt references it via the ``{suggestion_guidelines}``
placeholder, substituted at the end of ``AnalystAgent._build_system_prompt``
(plain string replace — brace-safe, and it covers the frame, the core skill
body, and any per-mode taxonomy override). Each consumer adds only a short
grounding preamble saying what "the current focus" and "the whole trajectory"
mean in its context; the rationale itself lives here and nowhere else.
"""

SUGGESTION_GUIDELINES = """\
Each suggestion is written as **action (goal)** — two parts, in this exact
shape:

1. *The action* — a concrete, chart-producing instruction in the user's
   voice (≤8 words), executable as-is: name the data and the operation.
2. *The goal* — in parentheses immediately after, ≤6 words, plain language:
   what taking this move would let the user find out.

For example: `Break daily sales down by region (see where growth
concentrates)` · `Split price by fuel grade (check if the gap widens)`.

Use readable field wording rather than raw column identifiers (say "CO2
emissions", not "Value_co2_emissions_kt_by_country"), but only reference
fields that exist. Both parts describe a **move and its purpose**, never a
claim about what the data shows: the goal says what the user could *find
out*, not what they *would* find. Write "(see whether the spike repeats
yearly)", never "(the spike repeats yearly)". Keep the goal concrete and
jargon-free — no restating the action, no hedged filler like "learn more
about it".

Offer **2–4 suggestions**, composed from two ranges so the set covers both
depth and breadth:

- **1–2 near moves — grounded in the current focus**: drill into a detail,
  try a statistical technique, or pivot to a different angle on it.
- **1–2 far moves — grounded in the whole trajectory**: broaden the view —
  bring in another table or area not yet explored, or zoom out to a bigger
  pattern.

Make the set meaningfully distinct, and never suggest a chart that already
exists."""
